language: php
php:
  - 7.2
  - 7.3
env:
  global:
    - secure: WcjQwI+z0rHo9ssnpYzY3amp3SWI0zwbw9WFIh7SmYMBiY6EsE0f553mbWhtOCJCoB7lwtxgE1xjo5sSWX5M5vWEeYFUIDMfkwh6EJ3bEnVBMs10KDUhKDRtJ8e+V66YHMvvDXvgDhy2I6ox5gWWrPFZXyUEoyRLCgQtCeu/siytoNxjw73bqO4BgRSY/qk6Uf427FW/ApsTW1t07rC5ek3pg2o+Tpl25+ak1h7tWdyUl2vQfElo3lt66deXNDEqBhZmLqRhgoHi/WbYaHSx+X5yVvgmP8y1xsl7TJLamHKhzHG3+fd1KyahGEobBrpxJeRVGY1W4D+ujrXIj0Ci3nEuGXMKxrtHOCECicLdsMtPpySsMZIgTg0MjiYzT3p/kujzjNQF0nXwSG7Nezy5JdGV3z32ak7qrw/Dilwd2y6k7MUFt+U7dkL/RiuaidoSXXp8OQ+JM0mqkkmUVUHNQzUZLpxYm+o4obo6DwUEl6K9DJo1wsS/uCaqy94qSCXdN5wf95UTne1YRavGdJEDrnsSd2OSHRX6F+q6fzxwuT/HD3O1bBcpfSoXhLTuxeEcjlr/Av5fx4fLd8Ppm2Y0PLpYr9cloKRSFUAUFVBuEiZxkKjbQ2KR41v7mRLffEm60MeDg/9hpFH9b7vPznQQu1n3SOEoAFnHH/JWyCCxQag=
    - secure: s6XTRIlZBRlLX+LMYXr0JT90w0GeUB2hFXnmeQ3Z919teZ1ElCVjOwh+txtyjih07UuVVvUTo7UIqzG7gEJr6YRu8G09XUp5sIYMTHCKVNxuotH7u8lkIorgPgsxN5QBjcgbIQq6eWqDoNynKh3DbYip7mMMziI18Peu8nXbJAQhDv0C4J6AhqA81jS80xkGrVKUY2/q0CSMJIMRwMyny40/i4yHQgc5ZIOsui/Fy+zxJwcuE4D5k6y6orTtWDudH/Df6AzPq/yORtuDBCaUzrBiCYFkdHy/absTMfl9XJFu0o3oSqGjWaJKkRaq7/koLfmiu4XQcut3gMFVljEr5Cw4cJgfZRTs7RfRY2a1FiLTsO9vMWRWL+RcvoVMYf7eKlX2Ig8gXoHXw69ymvtDDUw9z2a2V0lUyfybkeLT5BxGgWQcfINIwikrl7kmN33G6VfeKOgakaV/jC1GueJY0ivn9aymacId+SI24uSGg3eK3ySUM4+KDtzlkwjmvkkfRER8mtaipyvXOhitiRNj+C5Ks0Sy9wZ7VjU71rOTTxh6uy/S+8Ow2CqWEFi2ld4nGPy7hmfTb5mPysVhL7/XgNn4D7QZ7eTHlpRCC/SfVqkXT5vHG1LRk8NzjKSfZkztUDa54ipwfSqSu+qveDJC68BDZ9tRhmCtX3Na1fdR3S4=
before_install:
  - pip install --user codecov
install:
  - echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > auth.json
  - echo $NOVA_USERNAME
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry npm install
script:
  - npm run production
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_script:
  - codecov
