language: php
php:
  - 7.2
  - 7.3
before_install:
  - pip install --user codecov
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - npm install
  - npm run production
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_script:
  - codecov
